name: Set up JUnit Report
description: Sets up JUnit Report
runs:
  using: "composite"
  steps:
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
        annotate_only: true
